[package]
name = "backend"
license = "MIT"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
chrono = "0.4.26"
env_logger = "0.10.0"
futures-util = "0.3.28"
log = "0.4.20"
rocket = "0.4.11"
tokio = { version = "1.31.0", features = ["full"] }
tokio-tungstenite = "0.20.0"
